from pathlib import Path

translations = {
  "Live TV": "Live-TV",
  "Favorites": "Favoriten",
  "On Demand": "Mediathek",
  "Movies": "Filme",
  "TV Shows": "Serien",
  "Settings": "Einstellungen",
  "Search": "Suche",
  "Your IPTV & Media Hub": "Deine IPTV- & Medienzentrale",
  "Android TV · Phone · Tablet": "Android TV · Handy · Tablet",
  "Sync via Google Account": "Über Google-Konto synchronisieren",
  "Sign in to mirror playlists, watch progress, reminders, and preferences across your devices.": "Melde dich an, um Wiedergabelisten, Wiedergabefortschritt, Erinnerungen und Einstellungen auf deinen Geräten zu synchronisieren.",
  "Off": "Aus",
  "On": "Ein",
  "Connect a Server": "Server verbinden",
  "Skip for now": "Vorerst überspringen",
  "Choose a Source": "Quelle auswählen",
  "Choose Source": "Quelle auswählen",
  "Choose a source": "Quelle auswählen",
  "Continue": "Weiter",
  "Not now": "Nicht jetzt",
  "Back": "Zurück",
  "Next": "Weiter",
  "Done": "Fertig",
  "Cancel": "Abbrechen",
  "Save": "Speichern",
  "Delete": "Löschen",
  "Remove": "Entfernen",
  "Edit": "Bearbeiten",
  "Add": "Hinzufügen",
  "Close": "Schließen",
  "Retry": "Erneut versuchen",
  "Refresh": "Aktualisieren",
  "Test": "Testen",
  "Apply": "Übernehmen",
  "Reset": "Zurücksetzen",
  "Enable": "Aktivieren",
  "Disable": "Deaktivieren",
  "Enabled": "Aktiviert",
  "Disabled": "Deaktiviert",
  "General": "Allgemein",
  "Appearance": "Darstellung",
  "Player": "Wiedergabe",
  "Movies & TV Shows": "Filme & Serien",
  "Remote Control": "Fernbedienung",
  "Sync": "Synchronisierung",
  "Developer": "Entwickler",
  "About": "Über",
  "Playlists": "Wiedergabelisten",
  "Add Playlist": "Wiedergabeliste hinzufügen",
  "Edit Playlist": "Wiedergabeliste bearbeiten",
  "Refresh EPG Data": "EPG-Daten aktualisieren",
  "Refresh Everything": "Alles aktualisieren",
  "Guide Window": "EPG-Zeitraum",
  "All Available": "Alles verfügbar",
  "All Channels": "Alle Sender",
  "Username is required": "Benutzername ist erforderlich",
  "Password is required": "Passwort ist erforderlich",
  "Dispatcharr API key is required": "Dispatcharr-API-Schlüssel ist erforderlich",
  "Xtream Codes username is required": "Xtream-Codes-Benutzername ist erforderlich",
  "Search movies, shows, programs…": "Filme, Serien und Sendungen suchen…",
  "Search movies, shows, programs...": "Filme, Serien und Sendungen suchen...",
  "Search recordings": "Aufnahmen suchen",
  "Search channels": "Sender suchen",
  "No results": "Keine Ergebnisse",
  "No Results": "Keine Ergebnisse",
  "No Recordings": "Keine Aufnahmen",
  "Record a program from the guide or Live TV.": "Nimm eine Sendung aus dem EPG oder Live-TV auf.",
  "Recording now": "Aufnahme läuft",
  "Recording Now": "Laufende Aufnahmen",
  "Watch from Start": "Von Anfang ansehen",
  "Jump to Live": "Zu Live springen",
  "Stop Recording": "Aufnahme stoppen",
  "Resume": "Fortsetzen",
  "Play": "Abspielen",
  "Pause": "Pause",
  "Play from Beginning": "Von Anfang abspielen",
  "Details": "Details",
  "Options": "Optionen",
  "Continue Watching": "Weiterschauen",
  "Scheduled": "Geplant",
  "Recent Recordings": "Letzte Aufnahmen",
  "Results": "Ergebnisse",
  "All Recordings": "Alle Aufnahmen",
  "Partial": "Unvollständig",
  "Recording": "Aufnahme",
  "Delete recording?": "Aufnahme löschen?",
  "Title": "Titel",
  "Description": "Beschreibung",
  "Jump To": "Springen zu",
  "Day": "Tag",
  "Today": "Heute",
  "Tomorrow": "Morgen",
  "Now": "Jetzt",
  "Manage Groups": "Gruppen verwalten",
  "All": "Alle",
  "None": "Keine",
  "Sort": "Sortieren",
  "Filter": "Filter",
  "Program Info": "Sendungsinfo",
  "Record": "Aufnehmen",
  "Reminder": "Erinnerung",
  "Set Reminder": "Erinnerung setzen",
  "Remove Reminder": "Erinnerung entfernen",
  "Channel": "Sender",
  "Channels": "Sender",
  "No guide data": "Keine EPG-Daten",
  "No program information": "Keine Sendungsinformationen",
  "Audio Track": "Audiospur",
  "Subtitle Track": "Untertitelspur",
  "Subtitles": "Untertitel",
  "Audio": "Audio",
  "Playback Speed": "Wiedergabegeschwindigkeit",
  "Sleep Timer": "Sleep-Timer",
  "Picture in Picture": "Bild-in-Bild",
  "Switch Stream": "Stream wechseln",
  "Switch Version": "Version wechseln",
  "Channel List": "Senderliste",
  "Recent Channels": "Letzte Sender",
  "Multiview": "Mehrfachansicht",
  "Add streams": "Streams hinzufügen",
  "Add Streams": "Streams hinzufügen",
  "Make Audio": "Audio aktivieren",
  "Full Screen": "Vollbild",
  "Fullscreen": "Vollbild",
  "Quality": "Qualität",
  "Auto": "Automatisch",
  "Default": "Standard",
  "Default Tab": "Standard-Tab",
  "Language": "Sprache",
  "Theme": "Design",
  "Dark": "Dunkel",
  "Light": "Hell",
  "System": "System",
  "Text Size": "Textgröße",
  "Player Settings": "Wiedergabe-Einstellungen",
  "Live TV Settings": "Live-TV-Einstellungen",
  "DVR Settings": "DVR-Einstellungen",
  "General Settings": "Allgemeine Einstellungen",
  "Appearance Settings": "Darstellung",
  "Remote Control Settings": "Fernbedienung",
  "Sync Settings": "Synchronisierung",
  "App Updates": "App-Updates",
  "Developer Settings": "Entwicklereinstellungen",
  "Open Source Licenses": "Open-Source-Lizenzen",
  "Licenses": "Lizenzen",
  "Check for Updates": "Nach Updates suchen",
  "Check for Update": "Nach Update suchen",
  "Update Available": "Update verfügbar",
  "Up to Date": "Aktuell",
  "Download": "Herunterladen",
  "Install": "Installieren",
  "Downloading…": "Wird heruntergeladen…",
  "Downloading...": "Wird heruntergeladen...",
  "Installing…": "Wird installiert…",
  "Installing...": "Wird installiert...",
  "A new release is being published. Try again in a minute.": "Eine neue Version wird gerade veröffentlicht. Versuche es in einer Minute erneut.",
  "Update check failed: ${outcome.message}": "Update-Prüfung fehlgeschlagen: ${outcome.message}",
  "Not enough free space to download the update.": "Nicht genügend freier Speicher zum Herunterladen des Updates.",
  "Download failed: ${t.message ?: t::class.simpleName}": "Download fehlgeschlagen: ${t.message ?: t::class.simpleName}",
  "A recording is in progress. Finish or stop it, then install the update.": "Eine Aufnahme läuft. Beende oder stoppe sie und installiere danach das Update.",
  "The downloaded update is missing. Download it again.": "Das heruntergeladene Update fehlt. Lade es erneut herunter.",
  "Install failed: ${t.message ?: t::class.simpleName}": "Installation fehlgeschlagen: ${t.message ?: t::class.simpleName}",
  "Install failed (status $status)": "Installation fehlgeschlagen (Status $status)",
  "The download is incomplete (size mismatch). Try again.": "Der Download ist unvollständig. Versuche es erneut.",
  "The downloaded file is not a readable APK.": "Die heruntergeladene Datei ist keine lesbare APK.",
  "The downloaded APK is not AerioTV (${archive.packageName}).": "Die heruntergeladene APK gehört nicht zu AerioTV Deutsch (${archive.packageName}).",
  "Could not read the APK's signing certificate.": "Das Signaturzertifikat der APK konnte nicht gelesen werden.",
  "The APK's signing certificate does not match this app. Refusing to install.": "Das Signaturzertifikat der APK passt nicht zu dieser App. Installation abgebrochen.",
  "network error": "Netzwerkfehler",
  "rate limited": "Zu viele Anfragen",
  "bad response: ${t.message}": "Ungültige Serverantwort: ${t.message}",
  "Would you like to close AerioTV?": "Möchtest du AerioTV Deutsch schließen?",
  "Close AerioTV": "AerioTV Deutsch schließen",
  "Playing on ${companionTvName ?: \"TV\"}": "Wiedergabe auf ${companionTvName ?: \"TV\"}",
  "Playing on $castDevice": "Wiedergabe auf $castDevice",
  "Episode": "Episode",
  "Searching for devices...": "Geräte werden gesucht...",
  "Streaming to Cast device": "Streaming zum Cast-Gerät",
  "AerioTV is relaying this channel to your TV": "AerioTV Deutsch überträgt diesen Sender auf deinen Fernseher",
  "Sports": "Sport",
  "Kids": "Kinder",
  "News": "Nachrichten",
  "Documentary": "Dokumentation",
  "Comedy": "Komödie",
  "Educational": "Bildung",
  "Music": "Musik",
  "Dispatcharr (Username & Password)": "Dispatcharr (Benutzername & Passwort)",
  "Dispatcharr Direct Connect - Username & Password": "Dispatcharr Direct Connect – Benutzername & Passwort",
  "Dispatcharr Direct Connect - Admin API Key": "Dispatcharr Direct Connect – Admin-API-Schlüssel",
  "Dispatcharr Direct Connect - Standard API Key": "Dispatcharr Direct Connect – Standard-API-Schlüssel",
  "Imported file is missing: ${local.name}. Re-import it from Edit Playlist.": "Die importierte Datei fehlt: ${local.name}. Importiere sie unter „Wiedergabeliste bearbeiten“ erneut.",
  "Your Dispatcharr account can view recordings but not manage them. ": "Dein Dispatcharr-Konto kann Aufnahmen ansehen, aber nicht verwalten. ",
  "Ask your server administrator for DVR manage access.": "Bitte deinen Serveradministrator um Berechtigung zur DVR-Verwaltung.",
  "Your Dispatcharr account does not have DVR access. ": "Dein Dispatcharr-Konto hat keinen DVR-Zugriff. ",
  "Your Dispatcharr account does not have access to movies. ": "Dein Dispatcharr-Konto hat keinen Zugriff auf Filme. ",
  "Your Dispatcharr account does not have access to TV shows. ": "Dein Dispatcharr-Konto hat keinen Zugriff auf Serien. ",
  "Catch-up is not enabled for your Dispatcharr account. ": "Catch-up ist für dein Dispatcharr-Konto nicht aktiviert. ",
  "Ask your server administrator to enable it.": "Bitte deinen Serveradministrator, den Zugriff zu aktivieren.",
  "Switching streams needs a Dispatcharr administrator account. ": "Zum Wechseln von Streams ist ein Dispatcharr-Administratorkonto erforderlich. ",
  "Ask your server administrator for access.": "Bitte deinen Serveradministrator um Zugriff.",
  "Your Dispatcharr account cannot change server playlists. ": "Dein Dispatcharr-Konto darf Server-Wiedergabelisten nicht ändern. ",
  "Your Dispatcharr account cannot read server settings. ": "Dein Dispatcharr-Konto darf Servereinstellungen nicht lesen. ",
  "The server refused this even though your Dispatcharr account has permission. ": "Der Server hat die Anfrage abgelehnt, obwohl dein Dispatcharr-Konto die Berechtigung besitzt. ",
  "This usually means a network restriction on the account (allowed networks). ": "Das deutet meist auf eine Netzwerkbeschränkung des Kontos hin. ",
  "Ask your server administrator to allow this device's network.": "Bitte deinen Serveradministrator, das Netzwerk dieses Geräts freizugeben."
}

gradle = Path("app/build.gradle.kts")
s = gradle.read_text(encoding="utf-8")
s = s.replace('applicationId = "com.aeriotv.android"', 'applicationId = "de.dgstudios.aeriotvde"')
s = s.replace('versionCode = 65', 'versionCode = 1')
s = s.replace('versionName = "0.5.9"', 'versionName = "0.5.9-de1"')
gradle.write_text(s, encoding="utf-8")

settings = Path("settings.gradle.kts")
s = settings.read_text(encoding="utf-8").replace('rootProject.name = "AerioTV"', 'rootProject.name = "AerioTV-Deutsch"')
settings.write_text(s, encoding="utf-8")

strings = Path("app/src/main/res/values/strings.xml")
s = strings.read_text(encoding="utf-8").replace('<string name="app_name">AerioTV</string>', '<string name="app_name">AerioTV Deutsch</string>')
strings.write_text(s, encoding="utf-8")

manifest = Path("app/src/main/AndroidManifest.xml")
s = manifest.read_text(encoding="utf-8").replace('android:scheme="aeriotv"', 'android:scheme="aeriotvde"')
manifest.write_text(s, encoding="utf-8")

updater = Path("app/src/github/java/com/aeriotv/android/core/update/UpdateChecker.kt")
s = updater.read_text(encoding="utf-8")
s = s.replace("https://api.github.com/repos/jonzey231/AerioTV-Android/releases/latest",
              "https://api.github.com/repos/daniel96865-a11y/AerioTV-Android/releases/latest")
updater.write_text(s, encoding="utf-8")

candidates = list(Path("app/src/main/java/com/aeriotv/android/feature").rglob("*.kt"))
candidates += [
    Path("app/src/main/java/com/aeriotv/android/Navigation.kt"),
    Path("app/src/main/java/com/aeriotv/android/MainActivity.kt"),
    Path("app/src/main/java/com/aeriotv/android/core/category/ProgramCategory.kt"),
    Path("app/src/main/java/com/aeriotv/android/core/data/SourceType.kt"),
    Path("app/src/main/java/com/aeriotv/android/core/data/capability/DispatcharrCapability.kt"),
    Path("app/src/main/java/com/aeriotv/android/core/data/repository/PlaylistRepository.kt"),
    Path("app/src/main/java/com/aeriotv/android/core/cast/hlsproxy/CastHlsProxyService.kt"),
    Path("app/src/github/java/com/aeriotv/android/core/update/GithubUpdateManager.kt"),
    Path("app/src/github/java/com/aeriotv/android/core/update/UpdateChecker.kt"),
]
changed = 0
replacements = 0
for p in candidates:
    if not p.exists():
        continue
    src = p.read_text(encoding="utf-8")
    dst = src
    for en, de in translations.items():
        old = '"' + en.replace('"', '\\"') + '"'
        new = '"' + de.replace('"', '\\"') + '"'
        count = dst.count(old)
        if count:
            dst = dst.replace(old, new)
            replacements += count
    dst = dst.replace('text = "AerioTV"', 'text = "AerioTV Deutsch"')
    if dst != src:
        p.write_text(dst, encoding="utf-8")
        changed += 1

readme = Path("README.md")
original = readme.read_text(encoding="utf-8")
note = """# AerioTV Deutsch

**Inoffizielle deutsche Modifikation von AerioTV for Android.**
Ausgangsprojekt: jonzey231/AerioTV-Android. Diese Variante wurde am 21.09.2026 verändert und übersetzt. Sie bleibt gemäß dem Ausgangsprojekt unter GNU GPL v3 oder später; LICENSE, LICENSE-EXCEPTIONS.md und THIRD_PARTY_LICENSES.md bleiben Bestandteil des Projekts.

Die Variante verwendet die eigene Android-App-ID de.dgstudios.aeriotvde und kann dadurch neben dem Original installiert werden.

---

"""
if not original.startswith("# AerioTV Deutsch"):
    readme.write_text(note + original, encoding="utf-8")

Path("GERMAN_TRANSLATION_STATUS.md").write_text(
    f"# Deutsche Variante\n\nErster Übersetzungslauf: {replacements} exakte UI-Textvorkommen in {changed} Dateien ersetzt.\n"
    "Technische IDs, API-Felder, URLs und Codec-Namen wurden absichtlich nicht übersetzt.\n",
    encoding="utf-8",
)
print(f"Translated {replacements} occurrences across {changed} files")


# Second pass: translate remaining deep UI surfaces identified by the focused audit.
second_pass = {
  "Drive Sync isn't set up yet": "Drive-Synchronisierung ist noch nicht eingerichtet",
  "This product uses the TMDB API but is not endorsed or certified by TMDB.": "Dieses Produkt verwendet die TMDB-API, wird aber nicht von TMDB unterstützt oder zertifiziert.",
  "TMDB data is used only after configuring a TMDB API key in Settings > App Behaviors.": "TMDB-Daten werden erst verwendet, nachdem unter Einstellungen ein TMDB-API-Schlüssel eingerichtet wurde.",
  "Restoring Your Data": "Deine Daten werden wiederhergestellt",
  "Pulling your synced setup from Google Drive": "Synchronisierte Einrichtung wird aus Google Drive geladen",
  "Channels & Guide": "Sender & EPG",
  "What should come in from Drive?": "Was soll aus Google Drive übernommen werden?",
  "You can change any of this later in Settings, and each ": "Du kannst dies später jederzeit in den Einstellungen ändern. Jede ",
  "Choose Source Type": "Quellentyp auswählen",
  "Select how you want to connect to your media source.": "Wähle aus, wie du dich mit deiner Medienquelle verbinden möchtest.",
  "Connect to Dispatcharr with your admin login or a personal API key ": "Verbinde dich mit Dispatcharr über deinen Admin-Zugang oder einen persönlichen API-Schlüssel ",
  "Xtream Codes API. Live TV, VOD movies & series.": "Xtream-Codes-API. Live-TV, VOD-Filme und Serien.",
  "Any M3U playlist URL. Works with Dispatcharr, any IPTV provider.": "Beliebige M3U-Wiedergabelisten-URL. Funktioniert mit Dispatcharr und IPTV-Anbietern.",
  "Test Connection": "Verbindung testen",
  "My IPTV Server": "Mein IPTV-Server",
  "Server URL": "Server-URL",
  "Paste your admin API key": "Admin-API-Schlüssel einfügen",
  "Use a Dispatcharr Admin API Key (System -> Users -> Edit User -> API & XC). ": "Verwende einen Dispatcharr-Admin-API-Schlüssel (System -> Benutzer -> Benutzer bearbeiten -> API & XC). ",
  "Username": "Benutzername",
  "Dispatcharr admin username": "Dispatcharr-Admin-Benutzername",
  "Password": "Passwort",
  "Dispatcharr admin password": "Dispatcharr-Admin-Passwort",
  "Use your Dispatcharr Dashboard password (System -> Users -> Account tab), ": "Verwende dein Dispatcharr-Dashboard-Passwort (System -> Benutzer -> Konto), ",
  "Save credentials and refresh automatically. AerioTV signs in with these ": "Zugangsdaten speichern und automatisch aktualisieren. AerioTV Deutsch meldet sich damit ",
  "XC Username": "XC-Benutzername",
  "XC Password": "XC-Passwort",
  "Enter your Xtream Codes server URL and credentials. Dispatcharr users: use your ": "Gib die Xtream-Codes-Server-URL und Zugangsdaten ein. Dispatcharr-Nutzer verwenden ",
  "Import M3U from a file instead": "M3U stattdessen aus einer Datei importieren",
  "Import XMLTV from a file instead": "XMLTV stattdessen aus einer Datei importieren",
  "Paste your M3U playlist URL. Works with Dispatcharr's /output/m3u, any IPTV ": "Füge die URL deiner M3U-Wiedergabeliste ein. Funktioniert mit Dispatcharr /output/m3u und IPTV-",
  "AerioTV uses this URL automatically whenever your server is reachable on ": "AerioTV Deutsch verwendet diese URL automatisch, wenn dein Server erreichbar ist über ",
  "Username & Password": "Benutzername & Passwort",
  "Fetch On Demand from this playlist": "Mediathek aus dieser Wiedergabeliste laden",
  "When off, this playlist's movies and TV shows aren't loaded into On Demand. Useful if you only want Live TV from this server, or if you have a second playlist that already provides On Demand. You can change this later in Settings.": "Wenn ausgeschaltet, werden Filme und Serien dieser Wiedergabeliste nicht in die Mediathek geladen. Nützlich, wenn du von diesem Server nur Live-TV möchtest oder eine zweite Wiedergabeliste bereits die Mediathek liefert. Dies kann später in den Einstellungen geändert werden.",
  "Default Recording Destination": "Standard-Speicherort für Aufnahmen",
  "Where recordings are saved by default. Server recording requires a Dispatcharr admin account. You can change this later in Settings > DVR.": "Legt fest, wo Aufnahmen standardmäßig gespeichert werden. Server-Aufnahmen benötigen ein Dispatcharr-Administratorkonto. Später unter Einstellungen > DVR änderbar.",
  "Guide Days": "EPG-Tage",
  "How many days of guide data to load, back and ahead. Dispatcharr only; other sources show what their guide carries.": "Wie viele Tage EPG-Daten rückwirkend und im Voraus geladen werden. Nur für Dispatcharr; andere Quellen zeigen die gelieferten EPG-Daten.",
  "Search for movies, shows, or EPG programs": "Nach Filmen, Serien oder EPG-Sendungen suchen",
  "No results for “${state.query}”": "Keine Ergebnisse für „${state.query}“",
  "Try a different search term or change the scope filter.": "Versuche einen anderen Suchbegriff oder ändere den Bereichsfilter.",
  "Live TV  ·  Movies  ·  Series": "Live-TV  ·  Filme  ·  Serien",
  "No tiles selected.": "Keine Kacheln ausgewählt.",
  "Add Channel": "Sender hinzufügen",
  "Change Channel": "Sender wechseln",
  "Remove Spotlight": "Hervorhebung entfernen",
  "Spotlight This Tile": "Diese Kachel hervorheben",
  "Hide Scrubber": "Zeitleiste ausblenden",
  "Show Scrubber": "Zeitleiste anzeigen",
  "Return to Live": "Zurück zu Live",
  "Add to Multiview": "Zur Mehrfachansicht hinzufügen",
  "Play (${selected.size})": "Abspielen (${selected.size})",
  "Close search": "Suche schließen",
  "Clear search": "Suche leeren",
  "Movie · $it": "Film · $it",
  "Movie": "Film",
  "Episode $e": "Episode $e",
  "Don't Show Again": "Nicht mehr anzeigen",
  "Tile 1 · Now playing · $nowTitle": "Kachel 1 · Läuft jetzt · $nowTitle",
  "Selected": "Ausgewählt",
  "Open": "Öffnen",
  "All Series": "Alle Serien",
  "Control a TV": "Fernseher steuern",
  "Show tab bar, ${tab.label}": "Tableiste anzeigen, ${tab.label}",
  "Refresh channels and guide": "Sender und EPG aktualisieren",
  "$retainedCount channels kept live": "$retainedCount Sender werden live gehalten",
  "Add More Categories": "Weitere Kategorien hinzufügen",
  "Toggle a bucket on to colour matching programmes. Select the swatch to override its hex.": "Aktiviere eine Kategorie, um passende Sendungen farblich zu markieren. Wähle das Farbfeld, um den Hex-Wert anzupassen.",
  "Match an XMLTV category substring and pick its colour. Useful for genres outside the built-in buckets (e.g. Horror, Anime).": "Ordne einen XMLTV-Kategorietext zu und wähle dessen Farbe. Nützlich für weitere Genres wie Horror oder Anime.",
  "Add custom category": "Eigene Kategorie hinzufügen",
  "No custom categories yet. Select + above to add one.": "Noch keine eigenen Kategorien. Wähle oben +, um eine hinzuzufügen.",
  "Add Custom Category": "Eigene Kategorie hinzufügen",
  "Edit Custom Category": "Eigene Kategorie bearbeiten",
  "Hex color": "Hex-Farbe",
  "Show remote hints": "Fernbedienungshinweise anzeigen",
  "Key reminders on Live TV and in the player": "Tastenhinweise in Live-TV und im Player",
  "Play Channels In": "Sender abspielen in",
  "$name  (current)": "$name  (aktuell)",
  "Lose your remote control customizations?": "Anpassungen der Fernbedienung zurücksetzen?",
  "Reset to Defaults": "Auf Standard zurücksetzen",
  "Playlist": "Wiedergabeliste",
  "No playlist loaded": "Keine Wiedergabeliste geladen",
  "Remote URL": "Externe URL",
  "Active Playlist": "Aktive Wiedergabeliste",
  "Set Active": "Als aktiv festlegen",
  "Refresh Playlist": "Wiedergabeliste aktualisieren",
  "Refresh LAN Detection": "LAN-Erkennung aktualisieren",
  "Delete Playlist": "Wiedergabeliste löschen",
  "Delete playlist?": "Wiedergabeliste löschen?",
  "Refresh Everything?": "Alles aktualisieren?",
  "Skip loading screen": "Ladebildschirm überspringen",
  "Land on Live TV instantly; data hydrates in the background": "Sofort Live-TV öffnen; Daten werden im Hintergrund geladen",
  "Resume last channel": "Letzten Sender fortsetzen",
  "Auto-start the last-played channel on launch.": "Beim Start automatisch den zuletzt abgespielten Sender öffnen.",
  "Follow the device orientation. When off, ": "Geräteausrichtung übernehmen. Wenn ausgeschaltet, ",
  "Refresh in the background": "Im Hintergrund aktualisieren",
  "Movies & Series": "Filme & Serien",
  "Type: ${sourceType.displayName}. To switch types, use Change Playlist.": "Typ: ${sourceType.displayName}. Zum Wechseln des Typs „Wiedergabeliste ändern“ verwenden.",
  "Save Changes": "Änderungen speichern",
  "Name and Server URL are required": "Name und Server-URL sind erforderlich",
  "Show Channel Logos": "Senderlogos anzeigen",
  "Show Channel Numbers": "Sendernummern anzeigen",
  "Show Channel Names": "Sendernamen anzeigen",
  "Display each channel's name in the Guide's channel column.": "Sendernamen in der Sender-Spalte des EPG anzeigen.",
  "Show Program Subtitles": "Sendungsuntertitel anzeigen",
  "Rounded corners in Guide view": "Abgerundete Ecken in der EPG-Ansicht",
  "Full program details in every guide cell": "Vollständige Sendungsdetails in jeder EPG-Zelle",
  "Channel Preview": "Sendervorschau",
  "A banner shows the highlighted program; cells keep the title and tags": "Ein Banner zeigt die markierte Sendung; Zellen behalten Titel und Markierungen",
  "Show program badges": "Sendungsmarkierungen anzeigen",
  "LIVE, NEW, and season/episode pills on the guide": "LIVE, NEU und Staffel-/Episodenmarkierungen im EPG",
  "Live TV List": "Live-TV-Liste",
  "Color Programs by Category": "Sendungen nach Kategorie einfärben",
  "Apply category tints to the guide and channel rows.": "Kategoriefarben auf EPG und Senderzeilen anwenden.",
  "Reset Colors to Defaults": "Farben auf Standard zurücksetzen",
  "Enable Debug Logging?": "Debug-Protokollierung aktivieren?",
  "Enable Logging": "Protokollierung aktivieren",
  "Disable Debug Logging?": "Debug-Protokollierung deaktivieren?",
  "The existing log file will be kept. You can share or clear it at any time.": "Die vorhandene Protokolldatei bleibt erhalten. Du kannst sie jederzeit teilen oder löschen.",
  "Delete All Logs?": "Alle Protokolle löschen?",
  "Delete All Logs": "Alle Protokolle löschen",
  "Active, writing to aerio_debug_logs.txt": "Aktiv, schreibt in aerio_debug_logs.txt",
  "Scroll through entries in the app": "Einträge direkt in der App ansehen",
  "Scan a QR code with your phone": "QR-Code mit dem Handy scannen",
  "Email, Messages, Drive, etc.": "E-Mail, Nachrichten, Drive usw.",
  "Removes the current log and rotated archives": "Löscht das aktuelle Protokoll und ältere Archive",
  "Network": "Netzwerk",
  "No log file to share yet.": "Noch keine Protokolldatei zum Teilen vorhanden.",
  "Select a setting": "Einstellung auswählen",
  "On your phone, scan the QR code or open this URL. ": "Scanne auf deinem Handy den QR-Code oder öffne diese URL. ",
  "QR code for the log download URL": "QR-Code für die Protokoll-Download-URL",
  "The server stops when you close this screen. ": "Der Server wird beendet, wenn du diese Seite schließt. ",
  "Could not start LAN server. Check the TV's network connection.": "LAN-Server konnte nicht gestartet werden. Prüfe die Netzwerkverbindung des Fernsehers.",
  "Sign-in cancelled or failed.": "Anmeldung abgebrochen oder fehlgeschlagen.",
  "Signed in as $email": "Angemeldet als $email",
  "Drive authorization failed.": "Drive-Autorisierung fehlgeschlagen.",
  "Sync enabled": "Synchronisierung aktiviert",
  "Signed out of Drive.": "Von Drive abgemeldet.",
  "Remote Button Map": "Fernbedienungstasten",
  "Part of App Preferences. Turn off on a device whose ": "Teil der App-Einstellungen. Auf einem Gerät ausschalten, dessen ",
  "Push Config to Drive": "Konfiguration zu Drive hochladen",
  "Overwrite the Drive backup with this device's setup": "Drive-Sicherung mit der Einrichtung dieses Geräts überschreiben",
  "Pull Config from Drive": "Konfiguration aus Drive laden",
  "Overwrite this device with the Drive backup": "Dieses Gerät mit der Drive-Sicherung überschreiben",
  "Clear Drive Data": "Drive-Daten löschen",
  "Push Config to Drive?": "Konfiguration zu Drive hochladen?",
  "Push to Drive": "Zu Drive hochladen",
  "Pull Config from Drive?": "Konfiguration aus Drive laden?",
  "Pull from Drive": "Aus Drive laden",
  "Credentials sync to your Drive": "Zugangsdaten mit deinem Drive synchronisieren",
  "Select Sign in with Google below to connect your account. AerioTV will ": "Wähle unten „Mit Google anmelden“, um dein Konto zu verbinden. AerioTV Deutsch wird ",
  "This build doesn't have a Google Cloud OAuth client configured, so ": "Für diesen Build ist kein Google-Cloud-OAuth-Client eingerichtet, daher ",
  "Signed in to Drive": "Bei Drive angemeldet",
  "Not signed in": "Nicht angemeldet",
  "Sign out": "Abmelden",
  "Sign in with Google": "Mit Google anmelden",
  "Check for updates": "Nach Updates suchen",
  "You're on the latest version.": "Du verwendest die neueste Version.",
  "Download AerioTV ${s.info.versionName}": "AerioTV Deutsch ${s.info.versionName} herunterladen",
  "Verifying download...": "Download wird geprüft...",
  "Install AerioTV ${s.info.versionName}": "AerioTV Deutsch ${s.info.versionName} installieren",
  "The license this app is distributed under": "Lizenz, unter der diese App veröffentlicht wird",
  "The license FFmpeg is distributed under": "Lizenz, unter der FFmpeg veröffentlicht wird",
  "The license the above are distributed under": "Lizenz, unter der die oben genannten Komponenten veröffentlicht werden",
  "Channel Logo": "Senderlogo",
  "Channel Name": "Sendername",
  "Program Name": "Sendungsname",
  "Program Time": "Sendezeit",
  "Program Subtitle": "Sendungsuntertitel",
  "Program Description": "Sendungsbeschreibung",
  "Pause & rewind live TV": "Live-TV pausieren & zurückspulen",
  "Buffer fullscreen live playback on this device": "Live-Wiedergabe im Vollbild auf diesem Gerät puffern",
  "Rewind up to": "Zurückspulen bis",
  "Keep recent channels live": "Letzte Sender live halten",
  "Buffer flipped-away channels in the background": "Verlassene Sender im Hintergrund weiter puffern",
  "Channels to keep": "Anzahl der Sender",
  "Skip back": "Zurückspringen",
  "Auto-Recover Frozen Streams": "Hängende Streams automatisch neu laden",
  "Reload a live stream that stops sending video. Off keeps the stream as-is through commercial-break stutters.": "Lädt einen Live-Stream neu, wenn kein Video mehr kommt. Aus lässt den Stream bei kurzen Werbepausen unverändert.",
  "Send AC-3 and E-AC-3 audio to your receiver untouched. Leave off if lip sync drifts.": "AC-3- und E-AC-3-Audio unverändert an den Receiver senden. Ausschalten, wenn Bild und Ton auseinanderlaufen.",
  "Up / Down channel change": "Senderwechsel mit Hoch/Runter",
  "Slide a finger up or down the brightness edge to dim or brighten the screen. Applies to this app only and is restored when you leave the player.": "Am Helligkeitsrand nach oben oder unten wischen, um das Bild heller oder dunkler zu stellen. Gilt nur in dieser App.",
  "Slide a finger up or down the other edge to change the media volume.": "Am anderen Rand nach oben oder unten wischen, um die Medienlautstärke zu ändern.",
  "Add a small gap between tiles for visual separation.": "Kleinen Abstand zwischen Kacheln für bessere Trennung hinzufügen.",
  "Output 1080p streams at 1080p and let the TV upscale. Off keeps the display at its native mode.": "1080p-Streams in 1080p ausgeben und den Fernseher hochskalieren lassen. Aus behält den nativen Anzeigemodus.",
  "Developer Website": "Entwickler-Webseite",
  "Report an Issue": "Problem melden",
  "No playlists added": "Keine Wiedergabelisten hinzugefügt",
  "Manage Playlists": "Wiedergabelisten verwalten",
  "Guide, groups, badges, colors": "EPG, Gruppen, Markierungen, Farben",
  "Library refresh, posters": "Bibliothek aktualisieren, Poster",
  "Recordings, buffers, storage": "Aufnahmen, Puffer, Speicher",
  "Startup, refresh, network": "Start, Aktualisierung, Netzwerk",
  "Customize remote buttons": "Fernbedienungstasten anpassen",
  "Check for new releases": "Nach neuen Versionen suchen",
  "Recording $id": "Aufnahme $id",
  "Watch from Beginning": "Von Anfang ansehen",
  "Save to Device": "Auf Gerät speichern",
  "Save failed: ${it.message}": "Speichern fehlgeschlagen: ${it.message}",
  "Saving to device": "Wird auf dem Gerät gespeichert",
  "Remove Commercials": "Werbung entfernen",
  "Comskip failed: ${it.message}": "Comskip fehlgeschlagen: ${it.message}",
  "Comskip started": "Comskip gestartet",
  "Start at Live": "Bei Live starten",
  "Stop failed: ${it.message}": "Stoppen fehlgeschlagen: ${it.message}",
  "Edit Recording": "Aufnahme bearbeiten",
  "Cancel Recording": "Aufnahme abbrechen",
  "Delete from Server": "Vom Server löschen",
  "Delete from Device": "Vom Gerät löschen",
  "Saved to device": "Auf Gerät gespeichert",
  "Save to device failed": "Speichern auf Gerät fehlgeschlagen",
  "My Recordings": "Meine Aufnahmen",
  "Scheduled (${state.scheduledCount})": "Geplant (${state.scheduledCount})",
  "Recording (${state.recordingCount})": "Aufnahme (${state.recordingCount})",
  "Clear All": "Alle löschen",
  "Couldn't load recordings: $err": "Aufnahmen konnten nicht geladen werden: $err",
  "Invalid recording id.": "Ungültige Aufnahme-ID.",
  "Recording updated.": "Aufnahme aktualisiert.",
  "Recording deleted.": "Aufnahme gelöscht.",
  "Clear all completed?": "Alle abgeschlossenen Aufnahmen löschen?",
  "Delete All": "Alle löschen",
  "Hold OK for options": "OK gedrückt halten für Optionen",
  "Local": "Lokal",
  "No change": "Keine Änderung",
  "Your whole library": "Deine gesamte Bibliothek",
  "Guide channel column": "Sender-Spalte im EPG",
  "Playlist switching keeps your data": "Beim Wechsel der Wiedergabeliste bleiben deine Daten erhalten",
  "Android TV: Guide only": "Android TV: Nur EPG",
  "New: Live Rewind": "Neu: Live-Zurückspulen",
  "Not Now": "Nicht jetzt",
  "Stream switch failed": "Streamwechsel fehlgeschlagen",
  "Switching stream...": "Stream wird gewechselt...",
  "Go Back": "Zurück",
  "Channel Unavailable": "Sender nicht verfügbar",
  "Retry Now": "Jetzt erneut versuchen",
  "Channel Not Available": "Sender nicht verfügbar",
  "This channel isn't in the active playlist. If you just ": "Dieser Sender befindet sich nicht in der aktiven Wiedergabeliste. Wenn du gerade ",
  "No Stream Assigned": "Kein Stream zugewiesen",
  "This channel doesn't have a stream yet. Event channels ": "Für diesen Sender ist noch kein Stream hinterlegt. Ereignissender ",
  "Close another stream, then press Retry.": "Schließe einen anderen Stream und wähle dann „Erneut versuchen“.",
  "${it.name} live recording": "${it.name} Live-Aufnahme",
  "Go Live": "Zu Live",
  "Add a multiview tile": "Kachel zur Mehrfachansicht hinzufügen",
  "Turn on Live Rewind in Settings to pause & rewind live TV": "Aktiviere Live-Zurückspulen in den Einstellungen, um Live-TV zu pausieren und zurückzuspulen",
  "Press ‹ to close": "Zum Schließen ‹ drücken",
  "Record Current Program": "Aktuelle Sendung aufnehmen",
  "Stream Info": "Stream-Info",
  "Show Video": "Video anzeigen",
  "Audio Only": "Nur Audio",
  "$mins minutes": "$mins Minuten",
  "No subtitle tracks reported by the stream.": "Der Stream meldet keine Untertitelspuren.",
  "No audio tracks reported by the stream.": "Der Stream meldet keine Audiospuren.",
  "Audio Sync": "Audio-Synchronisierung",
  "Positive plays audio later; negative plays it earlier.": "Positive Werte geben Audio später wieder, negative früher.",
  "No alternate streams available for this channel.": "Für diesen Sender sind keine alternativen Streams verfügbar.",
  "Channels you watch will show up here.": "Hier erscheinen die Sender, die du ansiehst.",
  "No channels in this group.": "Keine Sender in dieser Gruppe.",
  "Loading…": "Wird geladen…",
  "Video Not Supported": "Video nicht unterstützt",
  "This device cannot decode this copy's video format, ": "Dieses Gerät kann das Videoformat dieser Version nicht dekodieren, ",
  "Recording Ending": "Aufnahme endet",
  "This recording is about to reach its scheduled end.": "Diese Aufnahme erreicht gleich ihr geplantes Ende.",
  "Continue on Live TV": "Im Live-TV fortfahren",
  "Back to DVR": "Zurück zu DVR",
  "Player options": "Player-Optionen",
  "Delete Collection": "Sammlung löschen",
  "Move to Front": "Nach vorne verschieben",
  "Move to Back": "Nach hinten verschieben",
  "Add to Collection": "Zur Sammlung hinzufügen",
  "Add at Beginning": "Am Anfang hinzufügen",
  "Add at End": "Am Ende hinzufügen",
  "Starting soon on $channelName": "Beginnt bald auf $channelName",
  "Heads-up when a programme you set a reminder on is about to start.": "Benachrichtigung, wenn eine vorgemerkte Sendung bald beginnt.",
  "Sort channels": "Sender sortieren",
  "Catch-up available": "Catch-up verfügbar",
  "Add to Collection…": "Zur Sammlung hinzufügen…",
  "Watch": "Ansehen",
  "Remove from Multiview": "Aus Mehrfachansicht entfernen",
  "Add Channel to Collection": "Sender zu Sammlung hinzufügen",
  "Remove from ${active.name}": "Aus ${active.name} entfernen",
  "Remove from All Collections": "Aus allen Sammlungen entfernen",
  "No upcoming schedule available": "Keine kommenden EPG-Daten verfügbar",
  "No Favorites": "Keine Favoriten",
  "Long-press a channel in Live TV and tap Add to Favorites.": "Halte einen Sender in Live-TV gedrückt und wähle „Zu Favoriten hinzufügen“.",
  "Drag to reorder": "Zum Sortieren ziehen",
  "Available Related Titles": "Verfügbare ähnliche Titel",
  "Poster and missing details pulled from TMDB using your API key.": "Poster und fehlende Details wurden mit deinem API-Schlüssel von TMDB geladen.",
  "Poster pulled from TMDB using your API key.": "Poster wurde mit deinem API-Schlüssel von TMDB geladen.",
  "Missing details filled in from TMDB using your API key.": "Fehlende Details wurden mit deinem API-Schlüssel von TMDB ergänzt.",
  "No artwork from your provider. Enter a TMDB API key in Settings > App Behaviors ": "Dein Anbieter liefert kein Bildmaterial. Hinterlege einen TMDB-API-Schlüssel in den Einstellungen ",
  "No matching title found on TMDB.": "Kein passender Titel auf TMDB gefunden.",
  "Series not found": "Serie nicht gefunden",
  "Couldn't load episodes: $error": "Episoden konnten nicht geladen werden: $error",
  "Server returned no episodes for this series.": "Der Server hat keine Episoden für diese Serie geliefert.",
  "Play in YouTube": "In YouTube abspielen",
  "Show QR Code": "QR-Code anzeigen",
  "View on TMDB": "Auf TMDB ansehen",
  "Season $season": "Staffel $season",
  "Movies needs Dispatcharr": "Filme benötigen Dispatcharr",
  "Search movies": "Filme suchen",
  "Couldn't load movies: $err": "Filme konnten nicht geladen werden: $err",
  "Search series": "Serien suchen",
  "Filter groups": "Gruppen filtern",
  "Open Series": "Serie öffnen",
  "Remove from Continue Watching": "Aus „Weiterschauen“ entfernen",
  "Movie not found": "Film nicht gefunden",
  "Cast & Crew": "Besetzung & Team",
  "No biography available.": "Keine Biografie verfügbar.",
  "Known For": "Bekannt für",
  "This series is too large to load on this device.": "Diese Serie ist zu groß, um auf diesem Gerät geladen zu werden.",
  "Casting": "Übertragung",
  "Cast": "Übertragen",
  "Cast to": "Übertragen auf",
  "Enter the code shown on ${companionConn.name ?: \"the TV\"}": "Gib den Code ein, der auf ${companionConn.name ?: \"dem Fernseher\"} angezeigt wird",
  "Connecting to ${companionConn.name ?: \"TV\"}...": "Verbindung zu ${companionConn.name ?: \"TV\"} wird hergestellt...",
  "Stop casting": "Übertragung beenden",
  "Switching to $it": "Wechsel zu $it",
  "No stream details available": "Keine Stream-Details verfügbar",
  "Now casting": "Wird übertragen",
  "Tap to resume": "Tippen zum Fortsetzen",
  "Resume audio": "Audio fortsetzen",
  "Pause audio": "Audio pausieren",
  "Return to player": "Zurück zum Player",
  "$count channels kept live": "$count Sender werden live gehalten",
  "Channel Groups": "Sendergruppen",
  "Hide options": "Optionen ausblenden",
  "More options": "Weitere Optionen",
  "Sort: ${sortMode.label}": "Sortieren: ${sortMode.label}",
  "Show List": "Liste anzeigen",
  "Show Guide": "EPG anzeigen",
  "No program description provided in XMLTV.": "Keine Sendungsbeschreibung in XMLTV vorhanden.",
  "For guides that only tag repeats.": "Für EPG-Daten, die nur Wiederholungen kennzeichnen.",
  "Match on every channel": "Auf allen Sendern abgleichen",
  "Off records only on ${target.channelName}.": "Aus nimmt nur auf ${target.channelName} auf.",
  "Pre-roll unavailable (program already started).": "Vorlauf nicht verfügbar (Sendung hat bereits begonnen).",
  "Dispatcharr server": "Dispatcharr-Server",
  "This device": "Dieses Gerät",
  "Saving to this device": "Wird auf diesem Gerät gespeichert",
  "Recording to the Dispatcharr server needs DVR manage access on your account. Contact your server administrator for more information.": "Für Aufnahmen auf dem Dispatcharr-Server benötigt dein Konto DVR-Verwaltungsrechte. Wende dich an deinen Serveradministrator.",
  "Remove commercials (Comskip)": "Werbung entfernen (Comskip)",
  "Detect and remove ad breaks after recording. Processed server-side.": "Werbeblöcke nach der Aufnahme erkennen und entfernen. Verarbeitung erfolgt auf dem Server.",
  "Step below zero to start the recording after the listed start time.": "Wähle einen Wert unter null, um die Aufnahme nach der angegebenen Startzeit zu beginnen.",
  "Record from Now": "Ab jetzt aufnehmen",
  "Record Program": "Sendung aufnehmen",
  "Save Rule": "Regel speichern",
  "Scheduling…": "Wird geplant…",
  "Drag to reorder, check to show or hide.": "Zum Sortieren ziehen; Häkchen zum Ein-/Ausblenden.",
  "No groups available": "Keine Gruppen verfügbar",
  "Shift guide moves the TV Guide over so the sidebar never covers programs.": "„EPG verschieben“ rückt den EPG zur Seite, damit die Seitenleiste keine Sendungen verdeckt.",
  "Default group": "Standardgruppe",
  "CHANNEL GROUPS": "SENDERGRUPPEN",
  "${retained.size} channels kept live": "${retained.size} Sender werden live gehalten",
  "Watch ${ch.channelName}": "${ch.channelName} ansehen",
  "Stop All": "Alle stoppen",
  "Kept Live": "Live gehalten",
  "No Matching Channels": "Keine passenden Sender",
  "No Channels in This Group": "Keine Sender in dieser Gruppe",
  "Show All Channels": "Alle Sender anzeigen",
  "Back to Now": "Zurück zu Jetzt",
  "Remove from Watchlist": "Von Merkliste entfernen",
  "Add to Watchlist": "Zur Merkliste hinzufügen",
  "Clear and close search": "Suche leeren und schließen",
  "Remove from Favorites": "Aus Favoriten entfernen",
  "Add to Favorites": "Zu Favoriten hinzufügen",
  "Cancel Reminder": "Erinnerung abbrechen",
  "Select a program": "Sendung auswählen",
  "Hide $contentLabel": "$contentLabel ausblenden",
  "Show $contentLabel": "$contentLabel anzeigen",
  "Show All Groups": "Alle Gruppen anzeigen",
  "On": "Ein",
  "Off": "Aus",
  "Back": "Zurück",
  "Cancel": "Abbrechen",
  "QR code for $title": "QR-Code für $title",
  "Close": "Schließen",
  "1 channel": "1 Sender",
  "$count channels": "$count Sender",
  "Ongoing notification while AerioTV plays audio in the background.": "Fortlaufende Benachrichtigung, während AerioTV Deutsch Audio im Hintergrund abspielt.",
  "Stream ended": "Stream beendet",
  "This stream was stopped by the server. Press Retry to start it again.": "Der Stream wurde vom Server beendet. Wähle „Erneut versuchen“, um ihn neu zu starten.",
  "Too many sessions playing": "Zu viele gleichzeitige Wiedergaben",
  "Server is busy": "Server ist ausgelastet",
  "All connections for this channel are in use right now. ": "Alle Verbindungen für diesen Sender sind derzeit belegt. ",
  "M3U URLs, Dispatcharr servers, Xtream credentials (server-side only)": "M3U-URLs, Dispatcharr-Server, Xtream-Zugangsdaten (nur serverseitig)",
  "Resume points for movies, episodes, and recordings": "Fortsetzungspunkte für Filme, Episoden und Aufnahmen",
  "Scheduled program reminders": "Geplante Sendungserinnerungen",
  "Favorite channels + your manual order": "Favorisierte Sender + deine manuelle Reihenfolge",
  "Movies and TV shows you saved for later, plus titles you hid": "Filme und Serien für später sowie ausgeblendete Titel",
  "Theme, appearance mode, accent color, default tab, hidden groups, palette overrides": "Design, Darstellungsmodus, Akzentfarbe, Standard-Tab, ausgeblendete Gruppen und Farbanpassungen",
  "Server passwords + API keys (Drive AppData is private to the app)": "Server-Passwörter + API-Schlüssel (Drive-AppData ist nur für die App sichtbar)",
  "Casting to $deviceName": "Übertragung auf $deviceName",
  "Can't cast this channel right now": "Dieser Sender kann derzeit nicht übertragen werden",
  "Event listing from the channel name; the provider has no guide data for it.": "Ereigniseintrag aus dem Sendernamen; der Anbieter liefert dafür keine EPG-Daten.",
  "Controls for the TV you are controlling from this phone": "Steuerung für den Fernseher, den du mit diesem Handy bedienst"
}

extra_candidates = list(Path("app/src/main/java/com/aeriotv/android/feature").rglob("*.kt"))
extra_candidates += list(Path("app/src/main/java/com/aeriotv/android/ui").rglob("*.kt"))
extra_candidates += [
    Path("app/src/main/java/com/aeriotv/android/Navigation.kt"),
    Path("app/src/main/java/com/aeriotv/android/core/tv/TvActionMenuDialog.kt"),
    Path("app/src/main/java/com/aeriotv/android/core/tv/TvQrLinkDialog.kt"),
    Path("app/src/main/java/com/aeriotv/android/core/playback/AutoBrowseTree.kt"),
    Path("app/src/main/java/com/aeriotv/android/core/playback/AerioMediaPlaybackService.kt"),
    Path("app/src/main/java/com/aeriotv/android/core/playback/DispatcharrConnectionLimit.kt"),
    Path("app/src/main/java/com/aeriotv/android/core/sync/SyncCategory.kt"),
    Path("app/src/main/java/com/aeriotv/android/core/cast/CastNotificationController.kt"),
    Path("app/src/main/java/com/aeriotv/android/core/cast/companion/CompanionRemoteService.kt"),
    Path("app/src/main/java/com/aeriotv/android/core/guide/GuideIndex.kt"),
    Path("app/src/github/java/com/aeriotv/android/core/update/GithubUpdateManager.kt"),
]
second_changed = 0
second_replacements = 0
for p in extra_candidates:
    if not p.exists():
        continue
    src = p.read_text(encoding="utf-8")
    dst = src
    for en, de in second_pass.items():
        old = '"' + en.replace('"', '\\"') + '"'
        new = '"' + de.replace('"', '\\"') + '"'
        count = dst.count(old)
        if count:
            dst = dst.replace(old, new)
            second_replacements += count
    if dst != src:
        p.write_text(dst, encoding="utf-8")
        second_changed += 1
print(f"Second pass: {second_replacements} occurrences across {second_changed} files")
